name: Lucas-blog deploy workflow

on:
  push:
    tags:
      - "*"
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy-and-sync:
    runs-on: ubuntu-latest
    
    env:
      NODE_ENV: production
      ESBUILD_BINARY_PATH: "node_modules/esbuild/bin/esbuild"

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          ref: "master"

      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9.15.0 --activate

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Install dependencies
        run: |
          pnpm config set registry https://registry.npmmirror.com/
          pnpm install --no-frozen-lockfile

      - name: Build Site
        run: pnpm run build

      - name: Ensure prod branch exists
        run: |
          git checkout --orphan prod || git checkout -b prod
          git commit --allow-empty -m "Initialize prod branch"
          git push origin prod

      - name: Deploy for Github 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: prod
          folder: docs/.vitepress/dist
          single-commit: true
          clean: true
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}